
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/assado_dba
        username: postgres
        password: postgres
    
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
        show-sql: true